// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextilePro.Core.DbContext;

#nullable disable

namespace TextilePro.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TextilePro.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableAffected")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TextilePro.Core.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelfDeclarationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("TextilePro.Core.Models.EvaluationAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("EvaluationAnswers");
                });

            modelBuilder.Entity("TextilePro.Core.Models.EvaluationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("EvaluationDocuments");
                });

            modelBuilder.Entity("TextilePro.Core.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChemicalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PurchaseMonth")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("TextilePro.Core.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("TextilePro.Core.Models.SupplierChemical", b =>
                {
                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChemicalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SupplierId", "ChemicalId");

                    b.HasIndex("ChemicalId");

                    b.ToTable("SupplierChemicals");
                });

            modelBuilder.Entity("TextilePro.Core.Models.SupplierContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierContacts");
                });

            modelBuilder.Entity("TextilePro.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            PasswordHash = "$2a$11$HT2tNH2XtgOcHRek0/vuuejbVnJOnYLcjmLglE7jOmO2ZBOQ7kIsC",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            PasswordHash = "$2a$11$flNTNcO6HTWl0wA0H8Ytnu7FYhMEJLo1JoxJ.1mfAbJ3PKh2fjiZC",
                            Username = "User"
                        });
                });

            modelBuilder.Entity("TextilePro.Core.Models.ZDHCChemical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChemicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalName")
                        .IsUnique();

                    b.ToTable("ZDHCChemicals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CAS = "64-19-7",
                            ChemicalName = "Acetic acid",
                            RiskCategory = "Non-Virgin",
                            Serial = "1",
                            UsageDescription = "For neutralisation purposes"
                        },
                        new
                        {
                            Id = 2,
                            CAS = "1336-21-6",
                            ChemicalName = "Ammonia solution",
                            RiskCategory = "Virgin",
                            Serial = "2",
                            UsageDescription = "pH adjustment"
                        },
                        new
                        {
                            Id = 3,
                            CAS = "1327-41-9",
                            ChemicalName = "Aluminium chloride hydroxide",
                            RiskCategory = "Non-Virgin",
                            Serial = "3",
                            UsageDescription = "Buffering agent, complexing agent"
                        },
                        new
                        {
                            Id = 4,
                            CAS = "10043-01-03",
                            ChemicalName = "Aluminium sulphate (Alum)",
                            RiskCategory = "Virgin",
                            Serial = "4",
                            UsageDescription = "Tanning, water treatment chemical"
                        },
                        new
                        {
                            Id = 5,
                            CAS = "1066-33-7",
                            ChemicalName = "Ammonium bicarbonate",
                            RiskCategory = "Virgin",
                            Serial = "5",
                            UsageDescription = "Neutralisation (leather processing)"
                        },
                        new
                        {
                            Id = 6,
                            CAS = "506-87-6",
                            ChemicalName = "Ammonium carbonate",
                            RiskCategory = "Virgin",
                            Serial = "6",
                            UsageDescription = "Mordant in textile dyeing"
                        },
                        new
                        {
                            Id = 7,
                            CAS = "12125-02-09",
                            ChemicalName = "Ammonium chloride",
                            RiskCategory = "Virgin",
                            Serial = "7",
                            UsageDescription = "Deliming (leather processing)"
                        },
                        new
                        {
                            Id = 8,
                            CAS = "7783-20-2",
                            ChemicalName = "Ammonium sulphate",
                            RiskCategory = "Virgin",
                            Serial = "8",
                            UsageDescription = "Levelling, after-treatment agents"
                        },
                        new
                        {
                            Id = 9,
                            CAS = "25155-25-3",
                            ChemicalName = "Bis peroxide",
                            RiskCategory = "Virgin",
                            Serial = "9",
                            UsageDescription = "Footwear-rubber"
                        },
                        new
                        {
                            Id = 10,
                            CAS = "10043-35-3",
                            ChemicalName = "Boric acid",
                            RiskCategory = "Virgin",
                            Serial = "10",
                            UsageDescription = "Deliming (leather processing)"
                        },
                        new
                        {
                            Id = 11,
                            CAS = "471-34-1",
                            ChemicalName = "Calcium carbonate",
                            RiskCategory = "Non-Virgin",
                            Serial = "11",
                            UsageDescription = "Accessory & gear"
                        },
                        new
                        {
                            Id = 12,
                            CAS = "12177-67-2",
                            ChemicalName = "Calcium hydroxide",
                            RiskCategory = "Non-Virgin",
                            Serial = "12",
                            UsageDescription = "Hair removal/liming (leather processing), ETP"
                        },
                        new
                        {
                            Id = 13,
                            CAS = "7778-54-3",
                            ChemicalName = "Calcium hypochlorite",
                            RiskCategory = "Virgin",
                            Serial = "13",
                            UsageDescription = "Bleaching, ETP, disinfecting chemicals"
                        },
                        new
                        {
                            Id = 14,
                            CAS = "9004-32-4",
                            ChemicalName = "Carboxymethyl cellulose (CMC)",
                            RiskCategory = "Virgin",
                            Serial = "14",
                            UsageDescription = "Weaving-sizing agent"
                        },
                        new
                        {
                            Id = 15,
                            CAS = "10141-00-1",
                            ChemicalName = "Chrome alum",
                            RiskCategory = "Non-Virgin",
                            Serial = "15",
                            UsageDescription = "Tanning"
                        },
                        new
                        {
                            Id = 16,
                            CAS = "10101-53-8",
                            ChemicalName = "Chromium sulphate",
                            RiskCategory = "Non-Virgin",
                            Serial = "16",
                            UsageDescription = "Chrome tanning"
                        },
                        new
                        {
                            Id = 17,
                            CAS = "77-92-9",
                            ChemicalName = "Citric acid anhydrous",
                            RiskCategory = "Virgin and Non-Virgin",
                            Serial = "17",
                            UsageDescription = "Neutralisation & buffering agent"
                        },
                        new
                        {
                            Id = 18,
                            CAS = "5949-29-1",
                            ChemicalName = "Citric acid monohydrate",
                            RiskCategory = "Virgin and Non-Virgin",
                            Serial = "18",
                            UsageDescription = "Neutralisation & buffering agent"
                        },
                        new
                        {
                            Id = 19,
                            CAS = "7783-28-0",
                            ChemicalName = "Diammonium phosphate",
                            RiskCategory = "Virgin",
                            Serial = "19",
                            UsageDescription = "Buffering agent in ETP"
                        },
                        new
                        {
                            Id = 20,
                            CAS = "7558-79-4",
                            ChemicalName = "Disodium phosphate",
                            RiskCategory = "Virgin",
                            Serial = "20",
                            UsageDescription = "Catalyst in pigment printing"
                        },
                        new
                        {
                            Id = 21,
                            CAS = "16389-88-1",
                            ChemicalName = "Dolomite",
                            RiskCategory = "Virgin",
                            Serial = "21",
                            UsageDescription = "Neutralisation (leather processing)"
                        },
                        new
                        {
                            Id = 22,
                            CAS = "67-43-6",
                            ChemicalName = "DTPA (Pentetic acid)",
                            RiskCategory = "Virgin",
                            Serial = "22",
                            UsageDescription = "Chelating agent"
                        },
                        new
                        {
                            Id = 23,
                            CAS = "60-00-4",
                            ChemicalName = "EDTA (Edetic acid)",
                            RiskCategory = "Virgin",
                            Serial = "23",
                            UsageDescription = "Chelating agent"
                        },
                        new
                        {
                            Id = 24,
                            CAS = "7705-08-0",
                            ChemicalName = "Ferric chloride",
                            RiskCategory = "Non-Virgin",
                            Serial = "24",
                            UsageDescription = "ETP chemical"
                        },
                        new
                        {
                            Id = 25,
                            CAS = "17375-41-6",
                            ChemicalName = "Ferrous sulphate",
                            RiskCategory = "Non-Virgin",
                            Serial = "25",
                            UsageDescription = "ETP chemical"
                        },
                        new
                        {
                            Id = 26,
                            CAS = "64-18-6",
                            ChemicalName = "Formic acid",
                            RiskCategory = "Non-Virgin",
                            Serial = "26",
                            UsageDescription = "Neutralisation substitute of acetic acid"
                        },
                        new
                        {
                            Id = 27,
                            CAS = "50-99-7",
                            ChemicalName = "Glucose",
                            RiskCategory = "Virgin",
                            Serial = "27",
                            UsageDescription = "Reducing agent"
                        },
                        new
                        {
                            Id = 28,
                            CAS = "56-81-5",
                            ChemicalName = "Glycerine",
                            RiskCategory = "Virgin",
                            Serial = "28",
                            UsageDescription = "Lab reagent, additive in printing"
                        },
                        new
                        {
                            Id = 29,
                            CAS = "7647-01-0",
                            ChemicalName = "Hydrochloric acid",
                            RiskCategory = "Non-Virgin",
                            Serial = "29",
                            UsageDescription = "Neutralisation substitute"
                        },
                        new
                        {
                            Id = 30,
                            CAS = "7722-84-1",
                            ChemicalName = "Hydrogen peroxide",
                            RiskCategory = "Virgin",
                            Serial = "30",
                            UsageDescription = "Bleaching agent, oxidising agent"
                        },
                        new
                        {
                            Id = 31,
                            CAS = "10039-54-0",
                            ChemicalName = "Hydroxylamine sulphate",
                            RiskCategory = "Virgin",
                            Serial = "31",
                            UsageDescription = "Buffering agent, hair removal"
                        },
                        new
                        {
                            Id = 32,
                            CAS = "142-91-6",
                            ChemicalName = "Isopropyl palmitate",
                            RiskCategory = "Virgin",
                            Serial = "32",
                            UsageDescription = "Textile processing"
                        },
                        new
                        {
                            Id = 33,
                            CAS = "127-68-4",
                            ChemicalName = "Sodium 3-nitrobenzenesulphonate",
                            RiskCategory = "Virgin",
                            Serial = "33",
                            UsageDescription = "Antioxidant in dyeing and printing"
                        },
                        new
                        {
                            Id = 34,
                            CAS = "546-93-0",
                            ChemicalName = "Magnesium carbonate",
                            RiskCategory = "Non-Virgin",
                            Serial = "34",
                            UsageDescription = "Neutralisation (leather processing)"
                        },
                        new
                        {
                            Id = 35,
                            CAS = "7786-30-3",
                            ChemicalName = "Magnesium chloride",
                            RiskCategory = "Non-Virgin",
                            Serial = "35",
                            UsageDescription = "ETP and textile complexing agent"
                        },
                        new
                        {
                            Id = 36,
                            CAS = "1309-42-8",
                            ChemicalName = "Magnesium hydroxide",
                            RiskCategory = "Non-Virgin",
                            Serial = "36",
                            UsageDescription = "Neutralisation (leather processing)"
                        },
                        new
                        {
                            Id = 37,
                            CAS = "7487-88-9",
                            ChemicalName = "Magnesium sulphate solution",
                            RiskCategory = "Non-Virgin",
                            Serial = "37",
                            UsageDescription = "Textile dyeing and leather tanning"
                        },
                        new
                        {
                            Id = 38,
                            CAS = "7697-37-2",
                            ChemicalName = "Nitric acid",
                            RiskCategory = "Non-Virgin",
                            Serial = "38",
                            UsageDescription = "Deionization ETP"
                        },
                        new
                        {
                            Id = 39,
                            CAS = "114-62-7",
                            ChemicalName = "Oxalic acid",
                            RiskCategory = "Virgin",
                            Serial = "39",
                            UsageDescription = "Neutraliser for polyester dyeing"
                        },
                        new
                        {
                            Id = 40,
                            CAS = "7664-38-2",
                            ChemicalName = "Phosphoric acid",
                            RiskCategory = "Virgin",
                            Serial = "40",
                            UsageDescription = "Buffering agent, neutralisation"
                        },
                        new
                        {
                            Id = 41,
                            CAS = "1327-41-9",
                            ChemicalName = "Polyaluminium chloride",
                            RiskCategory = "Non-Virgin",
                            Serial = "41",
                            UsageDescription = "Water and effluent treatment"
                        },
                        new
                        {
                            Id = 42,
                            CAS = "25322-68-3",
                            ChemicalName = "Polyethylene glycol",
                            RiskCategory = "Virgin",
                            Serial = "42",
                            UsageDescription = "Humectant, anti-foaming"
                        },
                        new
                        {
                            Id = 43,
                            CAS = "10043-67-1",
                            ChemicalName = "Potassium alum",
                            RiskCategory = "Virgin",
                            Serial = "43",
                            UsageDescription = "Water treatment"
                        },
                        new
                        {
                            Id = 44,
                            CAS = "7778-50-9",
                            ChemicalName = "Potassium dichromate",
                            RiskCategory = "Virgin",
                            Serial = "44",
                            UsageDescription = "After chroming agent in dyeing"
                        },
                        new
                        {
                            Id = 45,
                            CAS = "7778-77-0",
                            ChemicalName = "Potassium dihydrogen phosphate",
                            RiskCategory = "Non-Virgin",
                            Serial = "45",
                            UsageDescription = "Buffering"
                        },
                        new
                        {
                            Id = 46,
                            CAS = "1310-58-3",
                            ChemicalName = "Potassium hydroxide",
                            RiskCategory = "Virgin",
                            Serial = "46",
                            UsageDescription = "Lab reagent"
                        },
                        new
                        {
                            Id = 47,
                            CAS = "7722-64-7",
                            ChemicalName = "Potassium permanganate",
                            RiskCategory = "Virgin",
                            Serial = "47",
                            UsageDescription = "Denim fading, oxidising agent"
                        },
                        new
                        {
                            Id = 48,
                            CAS = "112926-00-8",
                            ChemicalName = "Silicon dioxide",
                            RiskCategory = "Virgin",
                            Serial = "48",
                            UsageDescription = "Footwear-rubber"
                        },
                        new
                        {
                            Id = 49,
                            CAS = "127-09-03",
                            ChemicalName = "Sodium acetate",
                            RiskCategory = "Non-Virgin",
                            Serial = "49",
                            UsageDescription = "Buffer in dyeing"
                        },
                        new
                        {
                            Id = 50,
                            CAS = "6131-90-4",
                            ChemicalName = "Sodium acetate trihydrate",
                            RiskCategory = "Non-Virgin",
                            Serial = "50",
                            UsageDescription = "Buffer in dyeing"
                        },
                        new
                        {
                            Id = 51,
                            CAS = "9005-38-3",
                            ChemicalName = "Sodium alginate",
                            RiskCategory = "Virgin",
                            Serial = "51",
                            UsageDescription = "Anti-migration in dyeing"
                        },
                        new
                        {
                            Id = 52,
                            CAS = "144-55-8",
                            ChemicalName = "Sodium bicarbonate",
                            RiskCategory = "Virgin",
                            Serial = "52",
                            UsageDescription = "Printing, neutralisation, buffer"
                        },
                        new
                        {
                            Id = 53,
                            CAS = "497-19-8",
                            ChemicalName = "Sodium carbonate",
                            RiskCategory = "Virgin",
                            Serial = "53",
                            UsageDescription = "Printing, neutralisation, buffer"
                        },
                        new
                        {
                            Id = 54,
                            CAS = "5968-11-6",
                            ChemicalName = "Sodium carbonate monohydrate",
                            RiskCategory = "Virgin",
                            Serial = "54",
                            UsageDescription = "Neutralisation, buffering agent"
                        },
                        new
                        {
                            Id = 55,
                            CAS = "6132-02-1",
                            ChemicalName = "Sodium carbonate decahydrate",
                            RiskCategory = "Virgin",
                            Serial = "55",
                            UsageDescription = "Dyeing agent for pH regulation"
                        },
                        new
                        {
                            Id = 56,
                            CAS = "7647-14-5",
                            ChemicalName = "Sodium chloride",
                            RiskCategory = "Non-Virgin",
                            Serial = "56",
                            UsageDescription = "Dyeing, bleaching, whitening"
                        },
                        new
                        {
                            Id = 57,
                            CAS = "6132-04-3",
                            ChemicalName = "Sodium citrate",
                            RiskCategory = "Non-Virgin",
                            Serial = "57",
                            UsageDescription = "WTP membrane cleaning"
                        },
                        new
                        {
                            Id = 58,
                            CAS = "7789-12-0",
                            ChemicalName = "Sodium dichromate",
                            RiskCategory = "Virgin",
                            Serial = "58",
                            UsageDescription = "After chroming agent in dyeing"
                        },
                        new
                        {
                            Id = 59,
                            CAS = "141-53-7",
                            ChemicalName = "Sodium formate",
                            RiskCategory = "Virgin",
                            Serial = "59",
                            UsageDescription = "Pickling (leather processing)"
                        },
                        new
                        {
                            Id = 60,
                            CAS = "7775-14-6",
                            ChemicalName = "Sodium hydrosulfite solid",
                            RiskCategory = "Virgin",
                            Serial = "60",
                            UsageDescription = "Discharge printing, ETP"
                        },
                        new
                        {
                            Id = 61,
                            CAS = "7775-14-6",
                            ChemicalName = "Sodium hydrosulfite solution",
                            RiskCategory = "Non-Virgin",
                            Serial = "61",
                            UsageDescription = "Dyeing, denim dyeing"
                        },
                        new
                        {
                            Id = 62,
                            CAS = "16721-80-5",
                            ChemicalName = "Sodium hydrosulphide",
                            RiskCategory = "Virgin",
                            Serial = "62",
                            UsageDescription = "Hair removal (leather processing)"
                        },
                        new
                        {
                            Id = 63,
                            CAS = "1310-73-2",
                            ChemicalName = "Sodium hydroxide pellets",
                            RiskCategory = "Non-Virgin",
                            Serial = "63",
                            UsageDescription = "Pre treatment & fixation"
                        },
                        new
                        {
                            Id = 64,
                            CAS = "1310-73-2",
                            ChemicalName = "Sodium hydroxide solution",
                            RiskCategory = "Non-Virgin",
                            Serial = "64",
                            UsageDescription = "Pre treatment, mercerising"
                        },
                        new
                        {
                            Id = 65,
                            CAS = "7681-52-9",
                            ChemicalName = "Sodium hypochlorite",
                            RiskCategory = "Virgin",
                            Serial = "65",
                            UsageDescription = "Oxidising agent, cleaning"
                        },
                        new
                        {
                            Id = 66,
                            CAS = "151-21-3",
                            ChemicalName = "Sodium lauryl sulphate",
                            RiskCategory = "Virgin",
                            Serial = "66",
                            UsageDescription = "Washing"
                        },
                        new
                        {
                            Id = 67,
                            CAS = "7681-57-4",
                            ChemicalName = "Sodium metabisulfite",
                            RiskCategory = "Virgin",
                            Serial = "67",
                            UsageDescription = "Anti oxidant"
                        },
                        new
                        {
                            Id = 68,
                            CAS = "6834-92-0",
                            ChemicalName = "Sodium metasilicate",
                            RiskCategory = "Virgin",
                            Serial = "68",
                            UsageDescription = "Alkali in CPB dyeing"
                        },
                        new
                        {
                            Id = 69,
                            CAS = "7631-99-4",
                            ChemicalName = "Sodium nitrate",
                            RiskCategory = "Virgin",
                            Serial = "69",
                            UsageDescription = "Textile enamel agent"
                        },
                        new
                        {
                            Id = 70,
                            CAS = "7632-00-0",
                            ChemicalName = "Sodium nitrite",
                            RiskCategory = "Not listed",
                            Serial = "70",
                            UsageDescription = "Neutraliser and buffer in tanning"
                        },
                        new
                        {
                            Id = 71,
                            CAS = "10486-00-7",
                            ChemicalName = "Sodium perborate",
                            RiskCategory = "Virgin",
                            Serial = "71",
                            UsageDescription = "Oxidising agent, filler"
                        },
                        new
                        {
                            Id = 72,
                            CAS = "15630-89-4",
                            ChemicalName = "Sodium percarbonate",
                            RiskCategory = "Virgin",
                            Serial = "72",
                            UsageDescription = "Oxidising agent, dye fixing"
                        },
                        new
                        {
                            Id = 73,
                            CAS = "7775-27-1",
                            ChemicalName = "Sodium persulfate",
                            RiskCategory = "Virgin",
                            Serial = "73",
                            UsageDescription = "Bleaching agent"
                        },
                        new
                        {
                            Id = 74,
                            CAS = "68915-31-1",
                            ChemicalName = "Sodium polyphosphates",
                            RiskCategory = "Virgin",
                            Serial = "74",
                            UsageDescription = "Buffer and alkali releasing"
                        },
                        new
                        {
                            Id = 75,
                            CAS = "1344-09-08",
                            ChemicalName = "Sodium silicate",
                            RiskCategory = "Virgin",
                            Serial = "75",
                            UsageDescription = "Silicate dyeing, fixing agent"
                        },
                        new
                        {
                            Id = 76,
                            CAS = "7757-82-6",
                            ChemicalName = "Sodium sulphate",
                            RiskCategory = "Non-Virgin",
                            Serial = "76",
                            UsageDescription = "Dyeing, ETP"
                        },
                        new
                        {
                            Id = 77,
                            CAS = "1313-82-2",
                            ChemicalName = "Sodium sulphide",
                            RiskCategory = "Non-Virgin",
                            Serial = "77",
                            UsageDescription = "Sulphur dyeing"
                        },
                        new
                        {
                            Id = 78,
                            CAS = "7757-83-7",
                            ChemicalName = "Sodium sulphite",
                            RiskCategory = "Non-Virgin",
                            Serial = "78",
                            UsageDescription = "Anti oxidant"
                        },
                        new
                        {
                            Id = 79,
                            CAS = "7772-98-7",
                            ChemicalName = "Sodium thiosulfate anhydrous",
                            RiskCategory = "Virgin",
                            Serial = "79",
                            UsageDescription = "Lab reagent, print film"
                        },
                        new
                        {
                            Id = 80,
                            CAS = "10102-17-7",
                            ChemicalName = "Sodium thiosulfate solution",
                            RiskCategory = "Virgin",
                            Serial = "80",
                            UsageDescription = "Lab reagent, print film"
                        },
                        new
                        {
                            Id = 81,
                            CAS = "65996-63-6",
                            ChemicalName = "Starch",
                            RiskCategory = "Virgin",
                            Serial = "81",
                            UsageDescription = "Finishing"
                        },
                        new
                        {
                            Id = 82,
                            CAS = "57-11-4",
                            ChemicalName = "Stearic acid",
                            RiskCategory = "Not listed",
                            Serial = "82",
                            UsageDescription = "Textile, footwear-rubber"
                        },
                        new
                        {
                            Id = 83,
                            CAS = "7664-93-9",
                            ChemicalName = "Sulphuric acid",
                            RiskCategory = "Non-Virgin",
                            Serial = "83",
                            UsageDescription = "ETP, carbonising"
                        },
                        new
                        {
                            Id = 84,
                            CAS = "1758-73-2",
                            ChemicalName = "Thio urea dioxide",
                            RiskCategory = "Virgin",
                            Serial = "84",
                            UsageDescription = "Reducing agent for dyeing"
                        },
                        new
                        {
                            Id = 85,
                            CAS = "7601-54-9",
                            ChemicalName = "Trisodium phosphate",
                            RiskCategory = "Non-Virgin",
                            Serial = "85",
                            UsageDescription = "Dyeing"
                        },
                        new
                        {
                            Id = 86,
                            CAS = "57-13-6",
                            ChemicalName = "Urea",
                            RiskCategory = "Not listed",
                            Serial = "86",
                            UsageDescription = "Printing humectant"
                        },
                        new
                        {
                            Id = 87,
                            CAS = "7446-20-0",
                            ChemicalName = "Zinc sulphate",
                            RiskCategory = "Non-Virgin",
                            Serial = "87",
                            UsageDescription = "Mordant in printing"
                        },
                        new
                        {
                            Id = 88,
                            CAS = "51839-25-9",
                            ChemicalName = "Zinc carbonate",
                            RiskCategory = "Non-Virgin",
                            Serial = "88",
                            UsageDescription = "Footwear-rubber"
                        });
                });

            modelBuilder.Entity("TextilePro.Core.Models.Evaluation", b =>
                {
                    b.HasOne("TextilePro.Core.Models.Supplier", "Supplier")
                        .WithMany("Evaluations")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TextilePro.Core.Models.EvaluationAnswer", b =>
                {
                    b.HasOne("TextilePro.Core.Models.Evaluation", "Evaluation")
                        .WithMany("Answers")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("TextilePro.Core.Models.EvaluationDocument", b =>
                {
                    b.HasOne("TextilePro.Core.Models.Evaluation", "Evaluation")
                        .WithMany("Documents")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("TextilePro.Core.Models.Inventory", b =>
                {
                    b.HasOne("TextilePro.Core.Models.ZDHCChemical", "Chemical")
                        .WithMany("Inventories")
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TextilePro.Core.Models.Supplier", "Supplier")
                        .WithMany("Inventories")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chemical");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TextilePro.Core.Models.SupplierChemical", b =>
                {
                    b.HasOne("TextilePro.Core.Models.ZDHCChemical", "Chemical")
                        .WithMany("SupplierChemicals")
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TextilePro.Core.Models.Supplier", "Supplier")
                        .WithMany("SupplierChemicals")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chemical");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TextilePro.Core.Models.SupplierContact", b =>
                {
                    b.HasOne("TextilePro.Core.Models.Supplier", "Supplier")
                        .WithMany("Contacts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TextilePro.Core.Models.Evaluation", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TextilePro.Core.Models.Supplier", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Evaluations");

                    b.Navigation("Inventories");

                    b.Navigation("SupplierChemicals");
                });

            modelBuilder.Entity("TextilePro.Core.Models.ZDHCChemical", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("SupplierChemicals");
                });
#pragma warning restore 612, 618
        }
    }
}
